### ISSUE TITLE
How did you figure out the graphql query?

### ISSUE THREAD

**Issue by rydes** [filippofinke/tutti-api#2]
Hello. Thanks for creating this project! I'm using the ideas and tricks behind it for my own side project. I'm very curious how did you get this graphql query. When i try inspecting network call from website i don't see anything like this. Did you maybe inspect the phone app? I would like to make similar query for getting the listing details. 
Ciao!

**Comment by filippofinke** [comment]
Hi there! 

Glad to hear you're finding the project helpful for your side project. 

The GraphQL query you mentioned can be found by inspecting the right network requests (in the browser). 

Have not had the necessity to inspect the phone app.

Good luck with your project! Ciao!
